Inspect pubsub behavior, optimize broadcasting
openmina/openmina pull request #883
Opened 2024-11-11 13:30 UTC by vlad9486

2024-11-27 12:27 UTC, tizoc commented on node/src/block_producer/block_producer_reducer.rs
> +                    dispatcher.push(p2p::P2pNetworkPubsubAction::Broadcast { message });
why is it not broadcasted after the `Inject` above? this means that it will be broadcasted even if the transition frontier rejects it right?

2024-11-27 12:29 UTC, tizoc commented on node/src/block_producer/block_producer_reducer.rs
> +                    dispatcher.push(p2p::P2pNetworkPubsubAction::Broadcast { message });
(I don't mean inside the `BlockInject` action itself but as the result of it, same way as other broadcasted blocks, after successful application and integration into the frontier)

2024-11-27 12:30 UTC, tizoc commented on p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs
> +                                    topic_id: dbg!(topic_id),
leftover `dbg!` here

2024-11-27 12:34 UTC, binier requested changes

2024-11-27 12:38 UTC, tizoc commented on node/testing/src/simulator/mod.rs
> +    pub async fn setup_and_run_with_listener<'a, AL, ALF>(
I think it is for that graphviz visualization?

2024-11-27 13:46 UTC, binier commented on node/testing/src/simulator/mod.rs
> +    pub async fn setup_and_run_with_listener<'a, AL, ALF>(
Yeah but it doesnt matter, it basically wraps action handler and doesnt add anything useful to the existing api. I just don't get why we need it.

2024-11-27 13:48 UTC, binier commented on node/testing/src/simulator/mod.rs
> +    pub async fn setup_and_run_with_listener<'a, AL, ALF>(
Oh it's for simulator code, mb. Ok it's fine for now, I'll clean up api afterwards.

2024-11-28 13:57 UTC, tizoc commented on p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs
> +            P2pNetworkPubsubAction::BroadcastBlock { block } => {
lets avoid this custom action is wrapping the `NewState` block in `Arc` works

2024-11-28 13:58 UTC, tizoc commented on node/src/block_producer/block_producer_reducer.rs
> +                dispatcher.push(p2p::P2pNetworkPubsubAction::BroadcastBlock {
@vlad9486 @binier  is this needed? shouldn't the best tip update logic itself handle it? otherwise how do we broadcast blocks that we didn't produce?

2024-11-28 13:58 UTC, tizoc commented on node/src/block_producer/block_producer_reducer.rs
> +                dispatcher.push(p2p::P2pNetworkPubsubAction::BroadcastBlock {
And if it is really needed, I would move it to `BlockInjected` bellow, we want to make sure we succeeded before broadcasting it right?

2024-11-29 18:25 UTC, tizoc commented
Superceded by https://github.com/openmina/openmina/pull/950 which already includes these changes

2024-11-30 01:25 UTC, tizoc commented
Closing in favor of #950 which already includes these changes

2024-12-01 15:02 UTC, closed without merging